# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Slovenia RUG
description:      Slovenia Ruby User Group
url:              http://www.rug.si
encoding:         utf-8

social:
  meetup:         http://www.meetup.com/RubySlovenia/
  twitter:        http://www.twitter.com/RubySlovenia/
  facebook:       https://www.facebook.com/groups/RubySlovenia/

author:
  name:           Miha Rekar
  url:            https://mr.si/
  email:          info@rug.si

paginate:         5

gems:
- jekyll-mentions
- jemoji
