# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Slovenia RUG
description:      Slovenia Ruby User Group
url:              http://www.rug.si
encoding:         utf-8

social:
  meetup:         http://www.meetup.com/RubySlovenia/
  twitter:        http://www.twitter.com/RubySlovenia/
  facebook:       https://www.facebook.com/groups/RubySlovenia/
  mailchimp:      http://eepurl.com/UHtR9

authors:
  mrfoto:
    name:           Miha Rekar
    url:            http://mr.si/
    email:          info@rug.si
  otobrglez:
    name:           Oto Brglez
    url:            http://otobrglez.opalab.com/
    email:          otobrglez@gmail.com
  zigomir:
    name:           Å½iga Vidic
    url:            https://twitter.com/zigomir
    email:          zigomir@gmail.com

paginate:         5

# defaults
sass:
    style:  expanded  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    # "deploy_style:" is used only for building the site
    # (ie: not using the --watch flag)

    compile_in_place: false   # true|false
    # If true, compiles sass directly into your jekyll source directory
    # As well as your destination directory

gems:
- jekyll-mentions
- jemoji
- jekyll-sitemap
- jekyll-sass
